name: Sphinx Template Difference Test

on:
  push:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Sphinx
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Generate Docs with Relative Path
        run: |
          mkdir -p relative_docs
          sphinx-apidoc -F -o ./relative_docs -A "author_name" -H "project_name" --templatedir ./templates .

      - name: Generate Docs with Full Path
        run: |
          mkdir -p full_docs
          sphinx-apidoc -F -o ./full_docs -A "author_name" -H "project_name" --templatedir ${{ github.workspace }}/templates .

      - name: Compare Generated Files
        run: |
          diff ./relative_docs/conf.py ./full_docs/conf.py || echo "Files differ"
